server:
  port: 7071

spring:
  application:
    name: card-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cards
    password: postgres
    username: postgres
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9001/

management:
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: info