server:
  port: 9001

oauth2-server:
  load-users: true
  load-roles: true
  cors-configuration:
    enabled: true
    allowed-origins: "*"
    allowed-origins-all: true
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
  customize-user-info-response: true

spring:
  application:
    name: oauth2-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authorization
    password: postgres
    username: postgres
  security:
    oauth2:
      authorizationserver:
        client:
          default-client:
            registration:
              client-id: "default-client"
              client-secret: "ZGVmYXVsdC1jbGllbnQ="
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "client_secret_jwt"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "*"
                - "http://127.0.0.1:7071/authorized"
                - "http://127.0.0.1:7071/swagger-ui/oauth2-redirect.html"
                - "http://localhost:7071/swagger-ui/oauth2-redirect.html"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

management:
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: info